### ISSUE TITLE
How do I customize the components?

### ISSUE THREAD

**Issue by aprilahijriyan** [ewilan-riviere/vue-tailwind-accordion#1]
For example, I want to change the border color when the item is active.

![Cuplikan layar dari 2020-11-30 20-41-22](https://user-images.githubusercontent.com/37798612/100616996-747fdd80-334c-11eb-9c04-2df1622137bc.png)

**Comment by srameshr** [comment]
@aprilahijriyan What did you do for this?

**Comment by aprilahijriyan** [comment]
Hmm, it looks like I don't use your components anymore. Sorry :( it's been a while ...
